/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Connection": {                                  "en": "Connection",                                      "de": "Verbindung",                                      "ru": "соединение",                                      "pt": "Conexão",                                         "nl": "Verbinding",                                      "fr": "Connexion",                                       "it": "Connessione",                                     "es": "Conexión",                                        "pl": "Połączenie",                                      "zh-cn": "连接"},
    "Connection settings": {                         "en": "Connection settings",                             "de": "Verbindungseinstellungen",                        "ru": "Настройки соединения",                            "pt": "Configurações de conexão",                        "nl": "Verbindingsinstellingen",                         "fr": "Paramètres de connexion",                         "it": "Impostazioni di connessione",                     "es": "Configuraciones de conexión",                     "pl": "Ustawienia połączenia",                           "zh-cn": "连接设定"},
    "Enabled": {                                     "en": "Enabled",                                         "de": "Ermöglicht",                                      "ru": "Включено",                                        "pt": "Habilitado",                                      "nl": "Ingeschakeld",                                    "fr": "Activée",                                         "it": "Abilitato",                                       "es": "Activado",                                        "pl": "Włączony",                                        "zh-cn": "启用"},
    "Page": {                                        "en": "Page",                                            "de": "Buchseite",                                       "ru": "Страница",                                        "pt": "Página",                                          "nl": "Bladzijde",                                       "fr": "Page",                                            "it": "Pagina",                                          "es": "Página",                                          "pl": "Strona",                                          "zh-cn": "页"},
    "Pages": {                                       "en": "Pages",                                           "de": "Seiten",                                          "ru": "Страницы",                                        "pt": "Páginas",                                         "nl": "Pagina's",                                        "fr": "Pages",                                           "it": "Pagine",                                          "es": "Paginas",                                         "pl": "Strony",                                          "zh-cn": "页面"},
};